spring.application.name=api
spring.jpa.show-sql=true
sping.jpa.hibernate.ddl-auto=update
jwt.secret=EsteEsUnSecretoMuySecretoPeronoSeLoDigasAAlguienPorqueEsMuySecretoMuySecreto
jwt.expiration=3600000


